import axios from "axios";
import type { DemoProduct } from "./type";

export const demoProducts: DemoProduct[] = [
  {
    _id: "1",
    name: "Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation.",
    price: 99.99,
    image: "/images/products/headphones.jpg",
    category: "Electronics",
    stock: 25,
    rating: 4.5,
  },
  {
    _id: "2",
    name: "Smart Watch",
    description: "Water-resistant smart watch with fitness tracking.",
    price: 149.99,
    image: "/images/products/smartwatch.jpg",
    category: "Electronics",
    stock: 40,
    rating: 4.2,
  },
  {
    _id: "3",
    name: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with deep bass.",
    price: 59.99,
    image: "/images/products/speaker.jpg",
    category: "Electronics",
    stock: 30,
    rating: 4.3,
  },
  {
    _id: "4",
    name: "Running Shoes",
    description: "Lightweight running shoes for men and women.",
    price: 79.99,
    image: "/images/products/shoes.jpg",
    category: "Footwear",
    stock: 50,
    rating: 4.6,
  },
  {
    _id: "5",
    name: "Backpack",
    description: "Durable backpack with multiple compartments.",
    price: 39.99,
    image: "/images/products/backpack.jpg",
    category: "Accessories",
    stock: 60,
    rating: 4.4,
  },
  {
    _id: "6",
    name: "Sunglasses",
    description: "UV-protected stylish sunglasses.",
    price: 24.99,
    image: "/images/products/sunglasses.jpg",
    category: "Accessories",
    stock: 80,
    rating: 4.1,
  },
  {
    _id: "7",
    name: "Coffee Maker",
    description: "Automatic coffee maker with programmable timer.",
    price: 89.99,
    image: "/images/products/coffeemaker.jpg",
    category: "Home Appliances",
    stock: 20,
    rating: 4.7,
  },
  {
    _id: "8",
    name: "Yoga Mat",
    description: "Non-slip yoga mat for all types of exercises.",
    price: 19.99,
    image: "/images/products/yogamat.jpg",
    category: "Fitness",
    stock: 100,
    rating: 4.5,
  },
  {
    _id: "9",
    name: "Laptop Stand",
    description: "Adjustable laptop stand for better ergonomics.",
    price: 29.99,
    image: "/images/products/laptopstand.jpg",
    category: "Office",
    stock: 35,
    rating: 4.3,
  },
  {
    _id: "10",
    name: "Desk Lamp",
    description: "LED desk lamp with touch control and dimmable light.",
    price: 22.99,
    image: "/images/products/desklamp.jpg",
    category: "Office",
    stock: 45,
    rating: 4.2,
  },
  {
    _id: "11",
    name: "Water Bottle",
    description: "Insulated stainless steel water bottle.",
    price: 14.99,
    image: "/images/products/waterbottle.jpg",
    category: "Fitness",
    stock: 120,
    rating: 4.6,
  },
  {
    _id: "12",
    name: "Gaming Mouse",
    description: "Ergonomic gaming mouse with customizable buttons.",
    price: 49.99,
    image: "/images/products/gamingmouse.jpg",
    category: "Electronics",
    stock: 55,
    rating: 4.4,
  },
  {
    _id: "13",
    name: "Wireless Charger",
    description: "Fast wireless charger compatible with all devices.",
    price: 27.99,
    image: "/images/products/wirelesscharger.jpg",
    category: "Electronics",
    stock: 70,
    rating: 4.3,
  },
  {
    _id: "14",
    name: "Fitness Tracker",
    description: "Track your daily activity and sleep patterns.",
    price: 59.99,
    image: "/images/products/fitnesstracker.jpg",
    category: "Fitness",
    stock: 65,
    rating: 4.2,
  },
  {
    _id: "15",
    name: "Electric Kettle",
    description: "Quick-boil electric kettle with auto shut-off.",
    price: 34.99,
    image: "/images/products/electrickettle.jpg",
    category: "Home Appliances",
    stock: 30,
    rating: 4.5,
  },
  {
    _id: "16",
    name: "Tablet",
    description: "10-inch tablet with high-resolution display.",
    price: 199.99,
    image: "/images/products/tablet.jpg",
    category: "Electronics",
    stock: 18,
    rating: 4.1,
  },
  {
    _id: "17",
    name: "Wireless Earbuds",
    description: "Compact wireless earbuds with charging case.",
    price: 69.99,
    image: "/images/products/earbuds.jpg",
    category: "Electronics",
    stock: 75,
    rating: 4.4,
  },
  {
    _id: "18",
    name: "Portable Hard Drive",
    description: "1TB portable hard drive for data storage.",
    price: 59.99,
    image: "/images/products/harddrive.jpg",
    category: "Electronics",
    stock: 40,
    rating: 4.6,
  },
  {
    _id: "19",
    name: "Desk Organizer",
    description: "Multi-compartment desk organizer for office supplies.",
    price: 17.99,
    image: "/images/products/deskorganizer.jpg",
    category: "Office",
    stock: 90,
    rating: 4.3,
  },
  {
    _id: "20",
    name: "Travel Mug",
    description: "Leak-proof travel mug for hot and cold drinks.",
    price: 16.99,
    image: "/images/products/travelmug.jpg",
    category: "Accessories",
    stock: 110,
    rating: 4.5,
  },
  {
    _id: "21",
    name: "Digital Camera",
    description: "Compact digital camera with 20MP sensor.",
    price: 249.99,
    image: "/images/products/camera.jpg",
    category: "Electronics",
    stock: 12,
    rating: 4.2,
  },
  {
    _id: "22",
    name: "Electric Toothbrush",
    description: "Rechargeable electric toothbrush with multiple modes.",
    price: 39.99,
    image: "/images/products/toothbrush.jpg",
    category: "Personal Care",
    stock: 60,
    rating: 4.4,
  },
  {
    _id: "23",
    name: "Hair Dryer",
    description: "Ionic hair dryer with cool shot button.",
    price: 29.99,
    image: "/images/products/hairdryer.jpg",
    category: "Personal Care",
    stock: 35,
    rating: 4.3,
  },
  {
    _id: "24",
    name: "Camping Tent",
    description: "Waterproof camping tent for 2-3 people.",
    price: 89.99,
    image: "/images/products/tent.jpg",
    category: "Outdoor",
    stock: 22,
    rating: 4.6,
  },
  {
    _id: "25",
    name: "Action Camera",
    description: "4K action camera with waterproof case.",
    price: 129.99,
    image: "/images/products/actioncamera.jpg",
    category: "Electronics",
    stock: 15,
    rating: 4.5,
  },
  {
    _id: "26",
    name: "Electric Scooter",
    description: "Foldable electric scooter with long battery life.",
    price: 399.99,
    image: "/images/products/scooter.jpg",
    category: "Outdoor",
    stock: 10,
    rating: 4.7,
  },
  {
    _id: "27",
    name: "Blender",
    description: "High-speed blender for smoothies and shakes.",
    price: 49.99,
    image: "/images/products/blender.jpg",
    category: "Home Appliances",
    stock: 28,
    rating: 4.4,
  },
  {
    _id: "28",
    name: "Wireless Keyboard",
    description: "Slim wireless keyboard with quiet keys.",
    price: 32.99,
    image: "/images/products/keyboard.jpg",
    category: "Electronics",
    stock: 50,
    rating: 4.3,
  },
  {
    _id: "29",
    name: "Men's Wallet",
    description: "Genuine leather wallet with RFID protection.",
    price: 21.99,
    image: "/images/products/wallet.jpg",
    category: "Accessories",
    stock: 70,
    rating: 4.5,
  },
  {
    _id: "30",
    name: "Women's Handbag",
    description: "Stylish handbag with spacious compartments.",
    price: 54.99,
    image: "/images/products/handbag.jpg",
    category: "Accessories",
    stock: 45,
    rating: 4.6,
  },
];

export const groupedByCategory = axios
  .get("http://localhost:3003/api/get-product")
  .then(async (res) => {
    const allProducts = Array.isArray(res.data.data)
      ? (res.data.data as DemoProduct[])
      : [];
    const groupedByCategoryP = allProducts.reduce((acc, product) => {
      const category = product.category;
      if (!acc[category]) {
        acc[category] = [];
      }
      acc[category].push(product);
      return acc;
    }, {} as Record<string, DemoProduct[]>);
    return groupedByCategoryP;
  });
